### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by ChriZzo2**

### CODE REVIEW

**Comment by ChriZzo2** [comment]
run build production

**Comment by ChriZzo2** [comment]
run build production

**Comment by ChriZzo2** [comment]
run build production

**Comment by prostore-blip** [comment]
run build production

**Comment by ChriZzo2** [comment]
run build production

**Comment by ChriZzo2** [comment]
run build production

**Comment by ChriZzo2** [comment]
run build production

**Comment by ChriZzo2** [comment]
run build production

**Comment by ChriZzo2** [comment]
run build production

**Review by prostore-blip — APPROVED** [review]

**Comment by prostore-blip** [comment]
run build production

**Comment by prostore-blip** [comment]
run build production

**Review by prostore-blip — DISMISSED** [review]

**Comment by prostore-blip** [comment]
run build production

**Comment by prostore-blip** [comment]
run build production

**Review by prostore-blip — DISMISSED** [review]

**Comment by prostore-blip** [comment]
run build production

**Review by voyager5874 — APPROVED** [review]

**Comment by voyager5874** [comment]
run build production

**Pull request merged**
